server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/interview
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
  graphql:
    graphiql:
      enabled: false
